### ISSUE TITLE
对csv批量情感分析可以吗

### ISSUE THREAD

**Issue by yanaoao** [foolfun/sentiment-analysis--web#1]
请问您这个可以对大型csv里面的每行文本进行批量情感分析吗？我看您的PPT是没有批量分析的

**Comment by foolfun** [comment]
你好，这是可以的，我所做的是对一个文本进行分析的网页形式，你可以另外自己写个代码，读取文件，调用模型，遍历每行文本，分析情感

**Comment by yanaoao** [comment]
![image](https://user-images.githubusercontent.com/28842732/113563756-da51de00-963a-11eb-9b1e-ff126f8b8b80.png)
您好，不好意思打扰啦。我想请问 这两个文件打开都是这三行代码，这三行代码是什么意思啊？？？？，那个网址点进去也只是一个关于github的网页，请问词向量的模型您放在文件夹了吗？？

**Comment by yanaoao** [comment]
谢谢您！！！！
